- inception_reports/generate_reports_lead.py
- inception_reports/generate_reports_manager.py
- tests/__init__.py
- tests/test_generate_reports_lead.py
- tests/test_generate_reports_manager.py
* Adding some unit tests.
* N/A.
> Feature 4 write unit tests

- inception_reports/__init__.py
- tests/test_generate_reports_lead.py
- tests/test_generate_reports_manager.py
- Fixed linter errors.
* Commits from ISSUE #8 regarding the usage of a linter.
* N/A
> [ISSUE #8]

- inception_reports/generate_reports_lead.py
- inception_reports/generate_reports_manager.py
A fix for plotting PHI annotations in from exported CAS files
Use the dashboard with an export INCEpTION project that contains PHI annotations.
> Bug 1 phi annotations dont get plotted

- inception_reports/generate_reports_manager.py
* Added option to select annotations type to count and plot.
* Dropped log scale from plot.
* Added type count to type label to make understanding the plots easier.
* Start the dashboard, and use the drop-down menu to select the annotation types you're interested in plotting. 
> Feature 3 support selection of annotation types

- inception_reports/__main__.py
- inception_reports/generate_reports_lead.py
- inception_reports/generate_reports_manager.py
- pyproject.toml
- tests/test_generate_reports_lead.py
- tests/test_generate_reports_manager.py
* Adds functionality to allow the users to input the path to the folder with imported INCEpTION projects in the frontend.
* Adds functionality to allow the users to import INCEpTION projects over API.
* Run it, and select one the abovementioned methods. 
> Feature 12 import inception project over api

- .gitignore
- README.md
- pyproject.toml
* Updated pyproject.toml to package the project properly
* Updated the README to explain how to use the package.
* N/A
> Feature 5 create a pypi package

- inception_reports/generate_reports_manager.py
* - Fixed #18
1. Start script.
2. Choose an import method.
3. Click Generate Reports
4. Admire the sidebar as it collapses but doesn't disappear.
> [ISSUE #18]

- inception_reports/generate_reports_manager.py
- Implemented features requested in #20 
- Cache the projects into the session state of streamlit.
- Use deepcopy to access them, because the session state is unstable.
1. Run script.
2. Import a project.
3. Measure how much time it takes.
4. Select/Deselect an annotation type.
5. Admire the speed at which the plot gets updated.
> Cache projects after import

- inception_reports/generate_reports_manager.py
* Implemented #22
* Hardcoded translations for code used in GeMTeX
* Also reorganzied functions
1. Create an INCEpTION project.
2. Add a code from one of these lists [1,2] to the description
3. Import the project into the Dashboard
4. The exported project status JSON object should contain the translated codes
> Feature 22 support reading special inception project tags

- MANIFEST.in
- inception_reports/generate_reports_lead.py
- inception_reports/generate_reports_manager.py
- pyproject.toml
* Fixed missing data files in the built python package.
* Removed hardcoded default values.
* Removed code used for demo purposes.
* N/A
> Bug 26 package data arent included in build

- inception_reports/generate_reports_manager.py
- Fixed error of project_tags being None by checking if it exists before using it.
* N/A
> Make project tags optional

- inception_reports/generate_reports_manager.py
- pyproject.toml
> Bug 33 access first item in dictionary without removing it

- .github/workflows/release_script.yml
- inception_reports/generate_reports_manager.py
* Fixed #35
* Changed the release pipeline to only run manually, until a better release strategy is decided.
* N/A
> Bug 35 login successful message despite failed login

- .gitignore
- inception_reports/__main__.py
- inception_reports/generate_reports_manager.py
- pyproject.toml
- Implemented function to get current package info.
- Implemented function to get latest released package version.
- Added functionality to show message to update the package in case they're not using the latest version.
- Update script argument to add shortcuts
* N/A
> Feature 42 check for package updates

- inception_reports/generate_reports_manager.py
- Fixed bug by checking if project description is set before using it.
- Added a check to raise an error in case the project doesn't contain any source documents.
* Start the script.
* Import a project without a description.
* Enjoy the lack of the errors.
> Bug 40 project without description

- inception_reports/generate_reports_lead.py
- Implemented functionality that allows uploading the files.
- If both a folder path is provided, and individual files are selected and uploaded, then the individual files take priority.
- Added the check for package updates from #42 to the lead view too.
* Run script in lead mode (--lead)
* See the option to select files to upload in the sidebar.
> Feature 41 allow selecting files for lead view

- inception_reports/generate_reports_manager.py
- Added current date as "created" to exported data
* Start script.
* Import project.
* Examine the exported data.
> Feature 47 add date to exported project data

- tests/test_generate_reports_manager.py
- Adjusted unit tests to reflect changes
* N/A
> #47 add date to exported project data

- README.md
- inception_reports/generate_reports_manager.py
* Added bar chart for subcategories of annotations
* Added button to switch between bar charts
* Run the Dashboard with a project that contains different annotations types, and use the button on the bar chart to switch between them.
> Feature 51 phi annotation on feature level

- inception_reports/generate_reports_manager.py
* Solved #54 by:
- Added fallback to INTIAL_CAS.json
- Removed resulting unneeded annotation type
* Follow the steps in #54
> #54 - Dashboard fails on unopen documents

- inception_reports/generate_reports_manager.py
- Stored the input directory in the streamlit session state
- Set the output directory to the input directory
1. Start Dashboard
2. Generate reports
3. The exported project data should be in the input directory
> #62 - Default output directory

- inception_reports/generate_reports_manager.py
- Added option to upload project files
- Added necessary logic to process uploaded files
- Updated project export message with export directory
Run the Dashboard, the new option should be visible under the "Manually" radio button.
> #73 - Upload project files

- inception_reports/generate_reports_manager.py
- pyproject.toml
- Add new function to create zip file of all generated reports
- Add download button for that zip
- Refactor the automatic export data to the main function
- Keep track of all generated reports
- Call the function to zip generated reports and create download button after all projects are processed
- Add creation timestamp to the project data
- Reformat code
- Update package version
* Run Dashboard
* Import project(s)
* Observe the majesty of the download button at the bottom of the page
> Download button

- inception_reports/generate_reports_manager.py
- pyproject.toml
- Clean type_counts by aggregating data
- Implement logic in get_type_counts to ensure consistency
- Filter the exported type_counts for document names to ensure data privacy
- Fix bar chart data handling to accommodate changes in type_counts
- Bump up package version
* Start Dashboard
* Import Project
* Generate Reports
* Inspect exported generated reports
> Export results of generated reports

- inception_reports/generate_reports_manager.py
- pyproject.toml
* Solves #86 
* Import a project with PHI annotations and documents in different states
* Check out the exported project data file to for PHI listed by document state
> Fine-grain PHI annotations

- inception_reports/generate_reports_manager.py
- Added dashboard version to exported JSON file for each project
* Import a project
* Check the exported JSON file to see the dashboard version used.
> Dashboard Version in Exported JSON

- inception_reports/generate_reports_manager.py
- Enhance project progress plotting to include document status breakdown for the total count
* Import project
* Generate report
* Inspect the exported JSON file for a breakdown of annotation count by document status
> #89 - Annotation Total Count by Status

- inception_reports/generate_reports_manager.py
- Adjusted code to handle the breakdown of features count by document status
- Fixed visibility management of the plot
* Import project
* Generate report
* Check the annotations count plot, and switch to fine-grain features overview to see the now visible bars
> #93 - Invisible Bars for PHI Annotations

- inception_reports/generate_reports_manager.py
- Checks for SNOMED annotaitons
- If found, gets label from KB using regex
- Displays them in Dashboard, and stores them in exported JSON
* Import project with SNOMED annotations and SNOMED knowledge base
* Look at stats about annotations
* Check out the stats in the exported JSON
> #96 - Process SNOMED Annotations

- inception_reports/generate_reports_manager.py
- Display current version and update availability in the Dashboard
* Start the Dashboard and look at the top of the sidebar
> #98 - Display Dashboard Version

- inception_reports/generate_reports_manager.py
- pyproject.toml
- Add function knowledge base ID from project metadata
- Add function to query the SPARQL endpoint of the INCEpTION API using batch querying
- Extract semantic tag from the last parentheses to solve #100
* Import a project with semantic tags
* Check the semantic tags in the right plot and exported project data
> 102 access kb over api
